#! /bin/bash

PROG=maestro

: ${PROG:=$(basename ${BASH_SOURCE})}

_cli_bash_autocomplete() {
  local cur opts base
  COMPREPLY=()
  _get_comp_words_by_ref cur prev
  opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )

  COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
  return 0
}

complete -F _cli_bash_autocomplete $PROG
